### ISSUE TITLE
Need favicon(s)

### ISSUE THREAD

**Issue by r-pop** [nkkl/afsea#2]
We need a 16x16 favicon, and optionally some larger ones as well.

**Comment by nkkl** [comment]
Checked in the 16x16!

**Comment by r-pop** [comment]
Deployed! <img width="211" alt="screen shot 2015-10-07 at 10 57 32 pm" src="https://cloud.githubusercontent.com/assets/11252938/10358795/d8e864bc-6d46-11e5-91eb-b2622cfce41a.png">
